// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlogAPI.Models;

public partial class Author
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}