// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlogAPI.Models;

public partial class Post
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int CategoryId { get; set; }

    public int AuthorId { get; set; }

    public virtual Author Author { get; set; }

    public virtual Category Category { get; set; }
}